# Generated by Django 5.2.7 on 2025-10-11 05:21

import ckeditor_uploader.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Rich formatted category description')),
                ('icon', models.CharField(blank=True, help_text='Icon name or URL', max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10)),
                ('url', models.URLField()),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Rich formatted API documentation')),
                ('path_params', models.JSONField(blank=True, default=list)),
                ('query_params', models.JSONField(blank=True, default=list)),
                ('is_premium', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apis', to='management.category')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='api_media/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='management.endpoint')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResponseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status_code', models.IntegerField(default=200)),
                ('media_type', models.CharField(default='application/json', max_length=100)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('body', models.JSONField(blank=True, default=dict)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='management.endpoint')),
            ],
            options={
                'ordering': ['status_code'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('accessed_at', models.DateTimeField(auto_now=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='management.endpoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'api')},
            },
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('status_code', models.IntegerField(default=200)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('request_body', models.JSONField(blank=True, default=dict)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='management.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('language', models.CharField(max_length=50)),
                ('request_type', models.CharField(help_text='Library or method (Requests, Axios, Fetch etc.)', max_length=50)),
                ('code_snippet', models.TextField(help_text='Example code snippet for this request type')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='management.endpoint')),
            ],
            options={
                'unique_together': {('api', 'language', 'request_type')},
            },
        ),
    ]
