# Generated by Django 5.2.7 on 2025-10-12 05:59

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Rich formatted Media documentation'),
        ),
    ]
