# Generated by Django 5.2.7 on 2025-10-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_api_id_alter_apicategory_id_and_more'),
        ('subscription', '0002_alter_subscriptionplan_id_alter_usersubscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='apis',
            field=models.ManyToManyField(related_name='plans', to='apis.api'),
        ),
    ]
