# Generated by Django 5.2.7 on 2025-10-10 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscriptionplan_apis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['-created_at']},
        ),
    ]
