# Generated by Django 5.2.7 on 2025-10-10 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_payment_metadata_alter_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
    ]
