# Generated by Django 5.2.7 on 2025-10-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_api_id_alter_apicategory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon name or URL', max_length=100),
        ),
    ]
