# Generated by Django 5.2.7 on 2025-10-10 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_apirequestlog_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apirequestlog',
            options={'ordering': ['-created_at']},
        ),
    ]
